apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vector
namePrefix: service-prd-vector-
commonLabels:
  env: prd

resources:
- deployment.yaml
- trigger_auth.yaml
- scaled_object.yaml
- configmap.yaml

images:
- name: asia-northeast3-docker.pkg.dev/project/prd-artifact-registry/vector-prd
  newName: asia-northeast3-docker.pkg.dev/project/prd-artifact-registry/vector-prd
  newTag: a123456
